### ISSUE TITLE
How to set the Client Id

### ISSUE THREAD

**Issue by WifiSen** [hxmelab/node-red-contrib-bosch-shc#20]
Hi

  I'm using node red on a raspi and want to connect to my BSHC. The search does not work, but  can ping the BSHC from my raspi. I can enter the IP manually but I can not enter an ID. When I try to pair anyway it says some information is missing. 

  Any hints? And what is the ID anyway?

Cheers
Wfif

**Comment by hxmelab** [comment]
Hi WifiSen,

the client id is auto generated and should fill the read only field of the shc configuration automatically. 

If this is not working for you, please check for updates and check the logs. Did you get an error?

Kind regards
Phil

**Comment by WifiSen** [comment]
Hi
  
  OK, I understand. I'm running node red on a raspi but not stand alone. It is an addon to homematic called redmatic. 

  My log shows the following:

Feb  9 23:49:52 ccu3-webui daemon.err node-red: (node:722) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded
Feb  9 23:49:52 ccu3-webui daemon.err node-red:     at getHttpClient.request.then.catch.error (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/huejay/lib/Transport.js:106:15)
Feb  9 23:49:52 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:68:7)
Feb  9 23:49:52 ccu3-webui daemon.err node-red: (node:722) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 203)

  I hope this can make things more clear.

Cheers,
Wifi

**Comment by WifiSen** [comment]
Hi Phil

  I checked the logfiles and all I see are some entries when the bosch node is loaded. Nothing else. I expected to see at least an error message when scanning for the BSHC fails, but nothing.

  How should the normal procedure look like after I have entered the IP manually? Just press Enter? How do I start the connection to the BSHC?

Cheers,
Wifi

**Comment by philbuettner** [comment]
When opening the configuration window for adding a new shc-config a message appears on the top of your window: "Generating new client data..." followed by "Generated!". This procedure is not only generating an id it is also generating a key and a certificate to communicate with the SHC. All the information will be posted with the pairing procedure. Hence, if these data is not getting generated it also won't work by just adding an id, because there are more information missing. 

What Node-RED version and what version of the shc-nodes are you using?

**Comment by hxmelab** [comment]
When opening the configuration window for adding a new shc-config a message appears on the top of your window: "Generating new client data..." followed by "Generated!". This procedure is not only generating an id it is also generating a key and a certificate to communicate with the SHC. All the information will be posted with the pairing procedure. Hence, if these data is not getting generated it also won't work by just adding an id, because there are more information missing.

What Node-RED version and what version of the shc-nodes are you using?

**Comment by WifiSen** [comment]
Hi

  When I open the window then the message "Generating new client data ..." appears but is followed by 2 "Not found" messages.

I use RedMatic 5.3.10  (https://github.com/rdmtc/RedMatic) which is node-red V1.0.3 togehther with shc-nodes V0.2.15.

**Comment by hxmelab** [comment]
To generate the client data two requests to the backend are necessary. It seems that the frontend is not able to get them.

Could you please check the requests and the output of the console? 
![image](https://user-images.githubusercontent.com/7083309/74269592-00674100-4d0a-11ea-86a4-1bd0842250c8.png)

**Comment by WifiSen** [comment]
That's what I see in the chrome console. 
![scsho](https://user-images.githubusercontent.com/52271283/74271915-fcd5b900-4d0d-11ea-811e-c42c3a37cf18.png)

**Comment by hxmelab** [comment]
Ok, this should be fixed with version 0.2.16. Thank you WifiSen for reporting and tribute to [hobbyquaker](https://github.com/hobbyquaker) who solves the bug.

**Comment by WifiSen** [comment]
Glad I could help. When can I expect 0.2.16?

**Comment by hxmelab** [comment]
It's available now...

**Comment by WifiSen** [comment]
... and it works!

Thank you very much for the quick response. Gut gemacht!

Grüße,
Wifi
